### PR TITLE
add support for client certificate authentication

### LINKED ISSUE #230: Configurable FTP client authentication method
I am trying to setup an FTP server with explicit TLS in my k8s cluster. It is great that most of the features I need are already available here. One thing that I am missing though is that username/password is the only way to authenticate the client today. It would be nice to have a hook for handleUser() in MainDriver interface where an implementer can decide on the authentication method, or do that internally by having an enum in the Settings struct. 

Wondering if there is any plan to support client authentication methods?
- Certificate Only: FTP clients must use certificate authentication
- Certificate or Password: FTP clients can use password or certificate authentication
- Certificate and Password: FTP clients must use password and certificate authentication

### PR DESCRIPTION
**Pull request by drakkan**
Fixes #230

Not yet tested with a real client

### CODE REVIEW

**Comment by sriramy** [comment]
Thanks a lot, this approach seems better, I agree.

Works for me using lftp
Success when user matches certificate subject + user exists in local DB: https://pastebin.com/fvMXnaMW
Failure to authenticate when user doesn't match certificate subject: https://pastebin.com/mKNp3Jux

**Comment by drakkan** [comment]
> Thanks a lot, this approach seems better, I agree.
> 
> Works for me using lftp

thanks for testing this patch

> Success when user matches certificate subject + user exists in local DB: https://pastebin.com/fvMXnaMW

```
---> USER ftp-client
<--- 230 TLS certificate ok, continue
```
good

> Failure to authenticate when user doesn't match certificate subject: https://pastebin.com/mKNp3Jux

```
---> USER ftp-client1
<--- 331 OK
---> PASS asdf
<--- 530 Authentication problem: No user ftp-client1 found
```

this is expected if your callback returns `nil, nil`. If you return an error the FTP client should receive a 530 response code for the `USER` command and should not try to send a password

**Comment by sriramy** [comment]
Yes, thank you, I was able to test all the three return variants to VerifyConnection()

// If it returns a non-nil error, the client will receive a 530 error and it will be disconnected.
https://pastebin.com/SMrCFp9y

// If it returns a nil error and a non-nil ClientDriver the client will be authenticated.
https://pastebin.com/8XHzLRhs

// If it returns a nil error and a nil ClientDriver the user password is required
https://pastebin.com/Rp8hgijw

**Comment by fclairamb** [comment]
Thank you to both of you, @sriramy for reporting this very real use-case of the library and @drakkan, as always, for this elegant implementation!

**Pull request merged**
