### PR TITLE
add support for TLS per-connection

### PR DESCRIPTION
**Pull request by drakkan**
Alternative approach to support TLS per-connection

### CODE REVIEW

**Comment by drakkan** [comment]
The test coverage misses are the same as #331 and #332 and so unrelated to this patch

**Review by fclairamb — APPROVED** [review]
I stay by what I said [here](https://github.com/fclairamb/ftpserverlib/pull/312/files#r885087924), it's much easier but adds one more field to the `ClientHandler`.

... which is fine. I'll start a discussion about this topic and ways to reduce the bloating memory footprint.

**Comment by drakkan** [comment]
> I stay by what I said [here](https://github.com/fclairamb/ftpserverlib/pull/312/files#r885087924), it's much easier but adds one more field to the `ClientHandler`.
> 
> ... which is fine. I'll start a discussion about this topic and ways to reduce the bloating memory footprint.

@fclairamb I don't want to force you to accept this PR instead of #312.  This is only to demostrate the alternative approach I proposed in #312. I prefer this one for the reasons explained there

**Comment by fclairamb** [comment]
Sorry I forgot to answer. Both options are fine to me, I prefer this code though.

**Comment by drakkan** [comment]
> Sorry I forgot to answer. Both options are fine to me, I prefer this code though.

Thanks, this code allows me to avoid checking if the property is set for the SFTPGo user every time a transfer connection is opened. I'll be adding this functionality to SFTPGo later today after a final code review

**Pull request merged**
