### PR TITLE
Add data channel (active/passive) information to the ClientContext interface

### PR DESCRIPTION
**Pull request by mmcgeefeedo**
This update will allow access to the last data channel mode, active or passive, based on the previous PORT or PASV commands. This update will enable us to record the data channel mode as part of SFTPGo's Upload/Download events.

### CODE REVIEW

**Comment by drakkan** [comment]
Hi,

I think this info can be useful. Maybe we could use an enum instead of hard coding the `active/passive` strings, but this is really a minor thing. 

Before making any changes, let's see what @fclairamb thinks of this patch. Thank you

**Comment by fclairamb** [comment]
The added value is pretty thin in my opinion but I'm fine with this change.

But yes, please turn into enums instead of strings.

**Review by drakkan — APPROVED** [review]

**Review by fclairamb — APPROVED** [review]
Perfect, thank you @mmcgeefeedo.

**Comment by fclairamb** [comment]
@mmcgeefeedo please update your branch and that should 😬 automatically merge it.

**Pull request merged**
