### PR TITLE
External client ID setter and getter.

### PR DESCRIPTION
**Pull request by awskii**
As far as we talking about ID method, i think it's true way - provide to users set their own external identifiers for client. So i implemented methods `SetID(id interface{})` and `ID() interface{}` to provide them such facility. Take a glance and let's discuss that.

### CODE REVIEW

**Comment by fclairamb** [comment]
## The client driver should be used instead
If you want to store client related data, you can implement it on the client driver. Have a look at the (recently updated) sample `ClientDriver`, it could have been implemented this way:
```go
// ClientDriver defines a very basic client driver
type ClientDriver struct {
	BaseDir string // Base directory from which to server file
        ID interface{} // <-- ADDED
}
```

## But still...
[The original discussion](https://github.com/fclairamb/ftpserver/pull/36#issuecomment-340357533) was around logging meaningful information from an app perspective. That's why I proposed to expose the Logger. I'm not so sure now (exposing variables exposes us to many things). We could see it another way, maybe add some logging context:
```go
func (c *clientHandler) AddLoggingContext(keyvals ...interface{}) {
	c.logger = log.With(c.logger, keyvals ...interface{})
}
```

That way when the user logs in, you could add some user context information. Here is a possible implementation of what that idea would look like on the current sample driver:
```go
// AuthUser authenticates the user and selects an handling driver
func (driver *MainDriver) AuthUser(cc server.ClientContext, user, pass string) (server.ClientHandlingDriver, error) {

	for _, act := range driver.config.Users {
		if act.User == user && act.Pass == pass {
			// If we are authenticated, we can return a client driver containing *our* basedir
			baseDir := driver.BaseDir + string(os.PathSeparator) + act.Dir
			os.MkdirAll(baseDir, 0777)
                        cc.AddLoggingContext( "userName", act.User ); // <-- ADDED
			return &ClientDriver{BaseDir: baseDir, ID: act.User}, nil
		}
	}

	return nil, fmt.Errorf("could not authenticate you")
}
```

**Comment by awskii** [comment]
@fclairamb I think, introduction of logger context could be helpful and logs will become more meaningful. But there should be a balance: user should have a way to configure what fields he\she wants to see in logs.

**Comment by awskii** [comment]
Also we forgot about exposing current active sessions counter, i create another PR for it.

**Comment by fclairamb** [comment]
I'm not convinced, I think this can be handled on the driver side. My goal is to avoid having any feature that could be implemented at a higher level.

**Pull request closed without merging**
