### PR TITLE
updated doc

### PR DESCRIPTION
**Pull request by awskii**
updated doc in accordance of new changes of api.

### CODE REVIEW

**Comment by asv** [comment]
@fclairamb off-topic question: our really need duplicate godoc in README.md?

**Comment by awskii** [comment]
I think, it's right way. New users will see API at front page of repository, it's convenient.

**Comment by asv** [comment]
This is not a common practice, in my opinion. Also it requires manual synchronization.

**Comment by fclairamb** [comment]
## Fixing the doc
No question there, it's good to keep the doc in sync with the API

## Having the API in the doc
It helps to give a clear understanding how it's supposed to be implemented. Maybe there's a better way to reach the same purpose. I'm open to suggestions. Showing a sample implementation would be perfect but also way too long.

**Review by fclairamb — APPROVED** [review]

**Pull request merged**
