### PR TITLE
Extending the clientcontext driver

### PR DESCRIPTION
**Pull request by fclairamb**
Someone (Artem) contacted me by email and reported two things:
- Client handling driver didn't allow to get the client's IP address
- The logging part isn't clear enough

This PR intends to fix that

### CODE REVIEW

**Comment by fclairamb** [comment]
So @awskii and the others, what do you think ?

**Comment by awskii** [comment]
Why you chose `uint32` for ID? I think, it should be `interface{}` or `string`. Why? E.g. you need to search some user activities in logs, but when you looking for ID = 1.. (any other < 256) you will see almost all log entries. At the same time, with interface or string i can set uuid which will be matched with exactly user what i looked for. 

Good that you fixed unsafe variable.

**Comment by fclairamb** [comment]
So let's see if I understand correctly,

# uint32

`uint32` is simply because the [sync/atomic](https://golang.org/pkg/sync/atomic/#AddUint32) methods accept exact types only.

# Logging and IDs

The `ID` is used to track the connection during its lifecycle (from connection to disconnection) and at the very first connection point. I understand that might not be ideal for logs handling.

## Integrating at the logger level

Still, the `ID` should probably kept during the complete duration of the connection. Maybe it could be a different kind of `ID`. Like `ConnectionID` for example.
Having to deal it with it in a specific way on the client level doesn't seem like a good thing. So I'm thinking maybe we could...

- Provide the `ClientContext` with the Logger as a interface method to the server 
- Pass it *before* logging the client arrival. 

That way the client driver could change the attributes to log if it wants to. By default, it could be a [nop logger](https://github.com/go-kit/kit/blob/master/log/nop_logger.go). So what you would have to do is something like:

```go
// WelcomeUser is called to send the very first welcome message
func (driver *MainDriver) WelcomeUser(cc server.ClientContext) (string, error) {
        cc.SetLogger( log.With(driver.Logger, "connectionId", myIdCounter)
	return fmt.Sprintf("Welcome on ftpserver, you're on dir %s", driver.BaseDir), nil
}
```

So at this point, we've added a `connectionId` to all the logs.

The server would log the connection on the client's logger, and only then send the message.

Then let's say that you want to add an `userId` once the user connects, you would have something like that:

```go
// AuthUser authenticates the user and selects an handling driver
func (driver *MainDriver) AuthUser(cc server.ClientContext, user, pass string) (server.ClientHandlingDriver, error) {
	user := driver.db.GetUser( user, pass );

        if ( user == nil ) {
            return nil, errors.New("Who are you ?")
        }

       clientDriver := NewClientDriver( cc )
       cc.SetLogger( log.With(cc.Logger(), "userId", user.ID ) );

	return clientDriver, nil
}
```

And now additionally to the `connectionId`, we also have a `userId` for all the exchanges that will follow. 

## Forgetting about logs

I'm also considering to completely drop logging. The [http package](https://golang.org/pkg/net/http/) allows to perform logging only through the use of intermediate handlers.

Which is something that could be done by using an intermediate driver. I'm not 100% sure it makes things simpler but it would allow to get rid of most of the logging problems. Not all of them though as the drivers doesn't report the exact socket exchanges.

# Unsafe variables

I'm not sure what you mean by unsafe variables.

**Comment by fclairamb** [comment]
Without any comment for days, i'm merging it.

**Pull request merged**
