### PR TITLE
fix: MLSD and MLST commands should write UTC timestamps

### PR DESCRIPTION
**Pull request by ottodashadow**
The NewFileInfo feels a little heavy-handed for what, in actuality, is a single-line change. @drakkan, the NewFileInfo will look familiar from the vfs package in sftpgo. If there's a better way to assert the rendered timestamp format or if you think the test is excessive, I can change it.

### CODE REVIEW

**Comment by drakkan** [comment]
Hi,

thank you for this patch, I'm not sure if @fclairamb agree, for a change like this I would omit the test case

**Review by fclairamb — APPROVED** [review]
LGTM

I feel like we could simplify the test case and make it a higher-level one (by using an FTP connection) but It's fine like this.

**Comment by drakkan** [comment]
Hi,

my only concern is about the licensing, we are incorporating some code (for the test cases) from sftpgo that is AGPLv3 sw, while ftpserverlib is MIT licensed. 

https://www.tawesoft.co.uk/kb/article/mit-license-faq#:~:text=Can%20I%20use%20GPL%2Dlicensed,still%20contain%20MIT%2Dlicensed%20software.

I have no problem to grant a license exception here, however I'll do some tests later today or this weekend to understand if we can write the test case differently

**Comment by drakkan** [comment]
Hi,

I think you can rewrite the test case this way:

```
func TestMLSDTimezone(t *testing.T) {
	s := NewTestServer(t, true)
	conf := goftp.Config{
		User:     authUser,
		Password: authPass,
	}

	c, err := goftp.DialConfig(conf, s.Addr())
	require.NoError(t, err, "Couldn't connect")

	defer func() { panicOnError(c.Close()) }()

	currentLocalTime := time.Local

	loc, err := time.LoadLocation("America/New_York")
	require.NoError(t, err)
	time.Local = loc

	ftpUpload(t, c, createTemporaryFile(t, 10), "file")
	contents, err := c.ReadDir("/")
	require.NoError(t, err)
	require.Len(t, contents, 1)
	require.Equal(t, "file", contents[0].Name())
	require.InDelta(t, time.Now().UTC().Unix(), contents[0].ModTime().UTC().Unix(), 5)
	
	time.Local = currentLocalTime
}
```

`ReadDir` uses MLSD by default.

Here is the relevant output:

```
level=debug ts=2021-05-27T09:09:59.018317874Z caller=client_handler.go:362 clientId=1 line="MLSD /" event="Received line"
level=debug ts=2021-05-27T09:09:59.018387119Z caller=client_handler.go:495 clientId=1 line="150 Using transfer connection" event="Sending answer"
level=debug ts=2021-05-27T09:09:59.018408122Z caller=client_handler.go:574 clientId=1 remoteAddr=127.0.0.1:55410 localAddr=127.0.0.1:42589 event="Transfer connection opened"
level=debug ts=2021-05-27T09:09:59.018444475Z caller=client_handler.go:249 clientId=1 event="Transfer connection closed"
level=debug ts=2021-05-27T09:09:59.018459258Z caller=client_handler.go:495 clientId=1 line="226 Closing transfer connection" event="Sending answer"
--- FAIL: TestMLSDTimezone (0.00s)
    /home/nicola/goprojects/ftpserverlib/handle_dirs_test.go:253: 
        	Error Trace:	handle_dirs_test.go:253
        	Error:      	Max difference between 1622106599 and 1622092199 allowed is 5, but difference was 14400
        	Test:       	TestMLSDTimezone
FAIL
FAIL	github.com/fclairamb/ftpserverlib	0.005s
FAIL
```

thank you

**Comment by drakkan** [comment]
changing the local time inside the test case seems to cause issues with the race detector. We have to remove that part from the test case and add a TestMain like this:

```
func TestMain(m *testing.M) {
	loc, err := time.LoadLocation("America/New_York")
	if err != nil {
		fmt.Printf("unable to set timezone: %v\n", err)
		os.Exit(1)
	}
	time.Local = loc
	os.Exit(m.Run())
}
```

**Comment by ottodashadow** [comment]
@drakkan thank you, I wouldn't have thought to change `time.Local` or use the `TestMain` function to solve the race condition.

**Comment by drakkan** [comment]
Thank you, before approving and so merging the PR, I will wait a few days to see if @fclairamb wants to change something. Maybe we could move the TestMain to another file (and maybe add a comment to explain why we need to change the timezone) but this could be also done after the merge

**Review by fclairamb — APPROVED** [review]

**Review by drakkan — APPROVED** [review]

**Comment by fclairamb** [comment]
@ottodashadow you can simply update your branch and it should be good.

**Pull request merged**
